// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzsebgorqklhojghzfwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6c2ViZ29ycWtsaG9qZ2h6ZndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTg2NzMsImV4cCI6MjA2NDY5NDY3M30.aguw-6L8PGXlEtYQCaWcCtBdx0Hecj9haBKznclEQw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);